config/routes.rb
DiatomOoze::Application.routes.draw do

  get "home/admin"

  resources :users do
    collection do 
      post "login"
    end
  end

  resources :enlists do
    collection do
      get "week_enlist"
    end
  end

  resources :games, :sites, :users, :teams

  get "home/login"
  match "home/enroll" => "users#enroll"
  match "home/enroll_success" => "home#enroll_success"

  root :to => 'home#index'

end

app/models/enlist.rb
class Enlist < ActiveRecord::Base
  attr_accessible :game_id, :user_id
  belongs_to :game
  belongs_to :user

  after_save :cal_balance

  def cal_balance
  	return if user.nil?
  	balance = user.balance
  	cost =  user.vip? ? 25 : 30
  	user.balance = balance - cost
  	user.save()
  end
end

app/controllers/enlists_controller.rb
class EnlistsController < ApplicationController
  # GET /enlists
  # GET /enlists.json
  def week_enlist
    @game = Game.find_by_id(params[:game_id])
    @users = @game.users
  end

  def index
    @enlists = Enlist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @enlists }
    end
  end

  # GET /enlists/1
  # GET /enlists/1.json
  def show
    @enlist = Enlist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @enlist }
    end
  end

  # GET /enlists/new
  # GET /enlists/new.json
  def new
    @enlist = Enlist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @enlist }
    end
  end

  # GET /enlists/1/edit
  def edit
    @enlist = Enlist.find(params[:id])
  end

  # POST /enlists
  # POST /enlists.json
  def create
    @enlist = Enlist.new(params[:enlist])

    respond_to do |format|
      if @enlist.save
        format.html { redirect_to @enlist, notice: 'Enlist was successfully created.' }
        format.json { render json: @enlist, status: :created, location: @enlist }
      else
        format.html { render action: "new" }
        format.json { render json: @enlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /enlists/1
  # PUT /enlists/1.json
  def update
    @enlist = Enlist.find(params[:id])

    respond_to do |format|
      if @enlist.update_attributes(params[:enlist])
        format.html { redirect_to @enlist, notice: 'Enlist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @enlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enlists/1
  # DELETE /enlists/1.json
  def destroy
    @enlist = Enlist.find(params[:id])
    @enlist.destroy

    respond_to do |format|
      format.html { redirect_to enlists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/enlists_helper.rb
module EnlistsHelper
end

app/views/enlists/_form.html.erb
<%= form_for(@enlist) do |f| %>
  <% if @enlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enlist.errors.count, "error") %> prohibited this enlist from being saved:</h2>

      <ul>
      <% @enlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_id %><br />
    <%= f.number_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enlists/edit.html.erb
<h1>Editing enlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @enlist %> |
<%= link_to 'Back', enlists_path %>

app/views/enlists/index.html.erb
<h1>Listing enlists</h1>

<table>
  <tr>
    <th>Game</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @enlists.each do |enlist| %>
  <tr>
    <td><%= enlist.game_id %></td>
    <td><%= enlist.user_id %></td>
    <td><%= link_to 'Show', enlist %></td>
    <td><%= link_to 'Edit', edit_enlist_path(enlist) %></td>
    <td><%= link_to 'Destroy', enlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Enlist', new_enlist_path %>

app/views/enlists/new.html.erb
<h1>New enlist</h1>

<%= render 'form' %>

<%= link_to 'Back', enlists_path %>

app/views/enlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Game:</b>
  <%= @enlist.game_id %>
</p>

<p>
  <b>User:</b>
  <%= @enlist.user_id %>
</p>


<%= link_to 'Edit', edit_enlist_path(@enlist) %> |
<%= link_to 'Back', enlists_path %>

app/views/enlists/week_enlist.html.erb
<div class="row get-started-now">
    <div class="span12 white-panel button-text-panel">
        <div class="white-panel-content">
            <h2><%= @game.game_date.strftime("%m月%d日") %>活动报名表！</h2>
            <a href="/home/enroll?game_id=<%= @game.try(:id) %>" class="btn btn-warning btn-large">报名</a>
        </div>
    </div>
</div>
<div class="row">
  <div class="span12 white-panel no-padding">
    <div class="tab-pane" id="profile">
      <div class="span5">
          <ul class="green-checks">
            <br/>
            <h2>目前报名人数：<%= @users.size %></h2>
            <% @users.each do |user|%>
              <li><h2><%= user.name %> | <%= user.balance %></h2></li>
            <% end %>
          </ul>

          
      </div>
    </div>
  </div>
</div>